function pug_rethrow(n,e,r,t){if(!(n instanceof Error))throw n;if(!("undefined"==typeof window&&e||t))throw n.message+=" on line "+r,n;try{t=t||require("fs").readFileSync(e,"utf8")}catch(e){pug_rethrow(n,null,r)}var i=3,a=t.split("\n"),o=Math.max(r-i,0),h=Math.min(a.length,r+i),i=a.slice(o,h).map(function(n,e){var t=e+o+1;return(t==r?"  > ":"    ")+t+"| "+n}).join("\n");throw n.path=e,n.message=(e||"Pug")+":"+r+"\n"+i+"\n\n"+n.message,n}function modal_tmpl(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {var pug_debug_sources = {"components\u002Fchat\u002Ftemplates\u002Fmodal.pug":"div.modal.modal__chat.not-visible\n  div.modal__body\n    div.modal__content\n      form.chat-login(name='chat-login')\n        fieldset\n          label(for='name') Enter yo name\n          input#name(type='text' placeholder='name' required autofocus)\n        button.button-primary.m-l-1.float-right(type='submit') Enter chat\n        button.button-outline.float-right.modal__chat-close(type='button') Close\n"};
;pug_debug_line = 1;pug_debug_filename = "components\u002Fchat\u002Ftemplates\u002Fmodal.pug";
pug_html = pug_html + "\u003Cdiv class=\"modal modal__chat not-visible\"\u003E";
;pug_debug_line = 2;pug_debug_filename = "components\u002Fchat\u002Ftemplates\u002Fmodal.pug";
pug_html = pug_html + "\u003Cdiv class=\"modal__body\"\u003E";
;pug_debug_line = 3;pug_debug_filename = "components\u002Fchat\u002Ftemplates\u002Fmodal.pug";
pug_html = pug_html + "\u003Cdiv class=\"modal__content\"\u003E";
;pug_debug_line = 4;pug_debug_filename = "components\u002Fchat\u002Ftemplates\u002Fmodal.pug";
pug_html = pug_html + "\u003Cform class=\"chat-login\" name=\"chat-login\"\u003E";
;pug_debug_line = 5;pug_debug_filename = "components\u002Fchat\u002Ftemplates\u002Fmodal.pug";
pug_html = pug_html + "\u003Cfieldset\u003E";
;pug_debug_line = 6;pug_debug_filename = "components\u002Fchat\u002Ftemplates\u002Fmodal.pug";
pug_html = pug_html + "\u003Clabel for=\"name\"\u003E";
;pug_debug_line = 6;pug_debug_filename = "components\u002Fchat\u002Ftemplates\u002Fmodal.pug";
pug_html = pug_html + "Enter yo name\u003C\u002Flabel\u003E";
;pug_debug_line = 7;pug_debug_filename = "components\u002Fchat\u002Ftemplates\u002Fmodal.pug";
pug_html = pug_html + "\u003Cinput id=\"name\" type=\"text\" placeholder=\"name\" required=\"required\" autofocus=\"autofocus\"\u002F\u003E\u003C\u002Ffieldset\u003E";
;pug_debug_line = 8;pug_debug_filename = "components\u002Fchat\u002Ftemplates\u002Fmodal.pug";
pug_html = pug_html + "\u003Cbutton class=\"button-primary m-l-1 float-right\" type=\"submit\"\u003E";
;pug_debug_line = 8;pug_debug_filename = "components\u002Fchat\u002Ftemplates\u002Fmodal.pug";
pug_html = pug_html + "Enter chat\u003C\u002Fbutton\u003E";
;pug_debug_line = 9;pug_debug_filename = "components\u002Fchat\u002Ftemplates\u002Fmodal.pug";
pug_html = pug_html + "\u003Cbutton class=\"button-outline float-right modal__chat-close\" type=\"button\"\u003E";
;pug_debug_line = 9;pug_debug_filename = "components\u002Fchat\u002Ftemplates\u002Fmodal.pug";
pug_html = pug_html + "Close\u003C\u002Fbutton\u003E\u003C\u002Fform\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line, pug_debug_sources[pug_debug_filename]);};return pug_html;}
